---
# tasks file for ansible-docker
- include_tasks: set_facts.yml

- include_tasks: alpine.yml
  when: ansible_os_family == "Alpine"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: config_docker.yml
  when: docker_config_service|bool

- include_tasks: service.yml

- include_tasks: users.yml
  when:
    - docker_config_users is defined
    - docker_config_users|bool

- include_tasks: images.yml
  when:
    - docker_manage_images|bool
    - docker_images is defined
