---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure Docker
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - bionic
        - precise
        - trusty
        - xenial
        - zesty
    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - cloud
    - development
    - packaging
    - system

dependencies: []
